### PR TITLE
merge Damianhodgkiss and nemos versions 

### PR DESCRIPTION
**Pull request by MC-Escherichia**
I grabbed the other two forks of this repo and pulled them together to get the functionality I wanted in terms of making the create_user function work.

### CODE REVIEW

**Comment by ibash** [comment]
@MC-Escherichia are you still interested in seeing this merged? It conflicts master on the execute method, if you resolve them I'd be happy to merge + publish. Thanks for the PR!

**Comment by MC-Escherichia** [comment]
@ibash I fixed conflicts, and this passes my company's internal tests.

**Comment by MC-Escherichia** [comment]
Also note that I pulled in @nemo 's work  so the commits under #3  are also here in #4

**Comment by nemo** [comment]
Sweet. This solves our problem – thanks @MC-Escherichia :)

**Comment by ibash** [comment]
Great! Thanks!

**Pull request merged**
